services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hangout-coffee

  hangout-coffee:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
